//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBS_MemberKYCDetails
    {
        public long ID { get; set; }
        public string MemberID { get; set; }
        public string KYC_AadharCard { get; set; }
        public string KYC_PanCard { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiyDate { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string VerifiedBy { get; set; }
        public string PassportPhoto { get; set; }
        public string KYC_AadharCard_back { get; set; }
        public string KYC_PanCard_back { get; set; }
    }
}
