//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class sbsjodhpurEntities : DbContext
    {
        public sbsjodhpurEntities()
            : base("name=sbsjodhpurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CityMaster> CityMasters { get; set; }
        public DbSet<CountryMaster> CountryMasters { get; set; }
        public DbSet<SBS_Employee_EducationCertificates> SBS_Employee_EducationCertificates { get; set; }
        public DbSet<SBS_Employee_IDProofs> SBS_Employee_IDProofs { get; set; }
        public DbSet<SBS_EmployeeMaster> SBS_EmployeeMaster { get; set; }
        public DbSet<StateMaster> StateMasters { get; set; }
        public DbSet<SBS_CategoryMaster> SBS_CategoryMaster { get; set; }
        public DbSet<SBS_Login> SBS_Login { get; set; }
        public DbSet<SBS_MemberKYCDetails> SBS_MemberKYCDetails { get; set; }
        public DbSet<SBS_ProductDetail> SBS_ProductDetail { get; set; }
        public DbSet<SBS_ProductMaster> SBS_ProductMaster { get; set; }
        public DbSet<SBS_RegistrationMaster> SBS_RegistrationMaster { get; set; }
    
        public virtual int SBS_GetDashboardData(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SBS_GetDashboardData", criteriaParameter);
        }
    
        public virtual int SBS_GetEmployeeDetails(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SBS_GetEmployeeDetails", criteriaParameter);
        }
    
        public virtual int SBS_GetMemberDetails(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SBS_GetMemberDetails", criteriaParameter);
        }
    
        public virtual ObjectResult<SBS_GetMemberKYCDetail_Result> SBS_GetMemberKYCDetail(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SBS_GetMemberKYCDetail_Result>("SBS_GetMemberKYCDetail", criteriaParameter);
        }
    
        public virtual int SBS_GetMemberReferralDetails(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SBS_GetMemberReferralDetails", criteriaParameter);
        }
    
        public virtual int SBS_GetProductCategory(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SBS_GetProductCategory", criteriaParameter);
        }
    
        public virtual ObjectResult<SBS_GetProductDetails_Result> SBS_GetProductDetails(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SBS_GetProductDetails_Result>("SBS_GetProductDetails", criteriaParameter);
        }
    
        public virtual int SBS_GetProducts(string criteria, string callBy)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            var callByParameter = callBy != null ?
                new ObjectParameter("CallBy", callBy) :
                new ObjectParameter("CallBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SBS_GetProducts", criteriaParameter, callByParameter);
        }
    
        public virtual int SBS_GetProductsDetails(string criteria)
        {
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SBS_GetProductsDetails", criteriaParameter);
        }
    
        public virtual ObjectResult<string> SBS_saveMemberKYCDetails(string memberID, string aadharCard, string panCard, string passportPhoto, string aadharCardBack, string panCardBack)
        {
            var memberIDParameter = memberID != null ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(string));
    
            var aadharCardParameter = aadharCard != null ?
                new ObjectParameter("AadharCard", aadharCard) :
                new ObjectParameter("AadharCard", typeof(string));
    
            var panCardParameter = panCard != null ?
                new ObjectParameter("PanCard", panCard) :
                new ObjectParameter("PanCard", typeof(string));
    
            var passportPhotoParameter = passportPhoto != null ?
                new ObjectParameter("PassportPhoto", passportPhoto) :
                new ObjectParameter("PassportPhoto", typeof(string));
    
            var aadharCardBackParameter = aadharCardBack != null ?
                new ObjectParameter("AadharCardBack", aadharCardBack) :
                new ObjectParameter("AadharCardBack", typeof(string));
    
            var panCardBackParameter = panCardBack != null ?
                new ObjectParameter("PanCardBack", panCardBack) :
                new ObjectParameter("PanCardBack", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SBS_saveMemberKYCDetails", memberIDParameter, aadharCardParameter, panCardParameter, passportPhotoParameter, aadharCardBackParameter, panCardBackParameter);
        }
    
        public virtual ObjectResult<SBS_Verifiy_KYC_Documents_Result> SBS_Verifiy_KYC_Documents(string memberID)
        {
            var memberIDParameter = memberID != null ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SBS_Verifiy_KYC_Documents_Result>("SBS_Verifiy_KYC_Documents", memberIDParameter);
        }
    
        public virtual ObjectResult<string> sp_MemberRegistration(string firstName, string lastName, string mobile, string email, Nullable<bool> gender, string city, string country, string memberReferralCode)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(bool));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var memberReferralCodeParameter = memberReferralCode != null ?
                new ObjectParameter("MemberReferralCode", memberReferralCode) :
                new ObjectParameter("MemberReferralCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_MemberRegistration", firstNameParameter, lastNameParameter, mobileParameter, emailParameter, genderParameter, cityParameter, countryParameter, memberReferralCodeParameter);
        }
    
        public virtual int usp_RandomPassword(Nullable<int> pass_len, ObjectParameter password)
        {
            var pass_lenParameter = pass_len.HasValue ?
                new ObjectParameter("pass_len", pass_len) :
                new ObjectParameter("pass_len", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RandomPassword", pass_lenParameter, password);
        }
    }
}
